baseURL: https://matyjb.pl/
languageCode: pl-pl
title: matyjb
theme: toha

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Enable Google Analytics
# googleAnalytics: UA-XXXXXXXXX-X

# Enable Disqus forum
# disqusShortname: does-not-exist

# Enable global emoji support
enableEmoji: true

# Custom parameters
params:
  # Copyright Notice
  # copyright: © 2020 Copyright.
  copyright: " "

  # Meta description for your site.  This will help the search engines to find your site.
  description: Portfolio Matyjb.

  # background image of the landing page
  background: "images/bg/bg4.jpg"

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  # It will be default to the theme logos if not provided.
  logo:
    main: images/logos/emblem.png
    # inverted: images/inverted-logo.png
    inverted: images/logos/emblem_bw.png

  # GitHub repo URL of your site
  gitRepo: https://github.com/matyjb/matyjb.github.io

  # specify whether you want to write blog post or not
  # enableBlogPost: true

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # specify the list of custom menus that you want to show in the top navbar.
  # they will be separated by a divider from the main menus.
  # customMenus:
  # - name: Notes
  #   url: https://hossainnotes.netlify.app/docs/example/

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: false

  # some information about you
  author:
    name: "Bartosz Matyjasiak"
    nickname: "matyjb"
    image: "images/avatar.jpg"
    # give your some contact information. they will be used in the footer
    contactInfo:
      email: "matyjasiakbartosz@gmail.com"
      instagram: "@matyjb"
      # phone: "+0123456789"
    # a summary of what you do
    summary:
    - Chcę zostać programistą
    - Lubię technologie webowe
    - Lubię wyzwania